# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ygQ5llWAeuZzS9coraGf5WkCWqC5AXH6
"""

!pip install pandas numpy scikit-learn matplotlib

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Load dataset
df = pd.read_csv("/content/StudentsPerformance.csv")  # Ensure the path is correct
print(df.head())

# Data Visualization
# Assuming the column for hours studied is named 'Hours Studied' or 'studytime'
# Replace 'Hours Studied' or 'studytime' with the actual column name if different
# Check the actual column names in your dataframe using df.columns
print(df.columns)  # Print the columns to find the correct name
# Replace 'actual_hours_studied_column' and 'actual_scores_column' with the correct column names
plt.scatter(df['reading score'], df['math score'], color='blue')
plt.title('Hours vs Marks')
plt.xlabel('Hours Studied')
plt.ylabel('Marks Obtained')
plt.show()

# Prepare Data
X = df[['reading score']]  # Independent variable (Study Hours)
y = df['math score']   # Dependent variable (Scores)

# Split data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict the scores for test data
y_pred = model.predict(X_test)

# Create a DataFrame for actual vs predicted values
df_results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print("\nActual vs Predicted:")
print(df_results)

# Plotting the regression line
plt.scatter(X, y, color='blue')
plt.plot(X, model.predict(X), color='red')
plt.title('Regression Line: Hours vs Marks')
plt.xlabel('Hours Studied')
plt.ylabel('Marks Obtained')
plt.show()

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f"\nMean Squared Error: {mse:.2f}")

# Predict a custom value (example: 9.25 hours)
hours = 9.25
predicted_score = model.predict([[hours]])
print(f"\nFor {hours} hours of study, the predicted score is: {predicted_score[0]:.2f}")